version: '3'
services:
  database:
    image: mysql:5.7
    container_name: locadora-db
    ports:
      - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123321
      MYSQL_DATABASE: 'db'
      MYSQL_USER: usuario
      MYSQL_PASSWORD: 123321