version: '3'
services:
  database:
    image: mariadb
    container_name: locadora-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123321
      MYSQL_DATABASE: 'db'
      MYSQL_USER: usuario
      MYSQL_PASSWORD: 123321